### ISSUE TITLE
init argument throws error

### ISSUE THREAD

**Issue by icrichmond** [robitalec/zarg#1]
Hello, 

Amazing package!! Thank you so much! 

I am running into trouble when I add an init argument to my `zar_brms()` function. Code: 

```{r}
  zar_brms(
    model_1,
    formula = response~ 1 + a + b+ c + (1 | site),
    family = gaussian(),
    prior = c( 
          prior(normal(0, 0.3), class = "b"),
          prior(normal(0, 0.3), class = "Intercept"),
          prior(exponential(1), class = "sd"),
          prior(exponential(1), class = "sigma")
        ),
    backend = 'cmdstanr',
    data = real_data_cooling,
    init = 0,
    chains = 2,
    iter = 1000,
    cores = 2
  )
```

>Error:
! Error running targets::tar_make()
  Error messages: targets::tar_meta(fields = error, complete_only = TRUE)
  Debugging guide: https://books.ropensci.org/targets/debugging.html
  How to ask for help: https://books.ropensci.org/targets/help.html
  Last error: unused argument (init = 0)

Not sure if this is something I am doing wrong or if the function didn't include this argument? 

Thanks again!

**Comment by robitalec** [comment]
The function didn't include this argument, I will add it in a PR!
